version: '3'

services:
  proxy:
    restart: unless-stopped
    build: proxy
    volumes:
      - ./proxy/Caddyfile:/etc/Caddyfile
      - ./proxy/.caddy:/root/.caddy
    ports:
      - "80:80"
      - "443:443"

  ghost:
    restart: unless-stopped
    build:
      context: ./ghost
      args:
        url: 'https://your.domain.here'
    volumes:
      - ./ghost/content:/var/lib/ghost/content/
    ports:
      - "2368"
